### ISSUE TITLE
Remove indentation in README block text? 

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/eeb430.2017.JuniorCoders#12]
The [README](https://github.com/UofTCoders/eeb430.2017.JuniorCoders/blob/master/README.md) is rendering weirdly for the first two paragraphs. I think if you remove the indent at the beginning of the paragraph on lines 10 and 14, it will display as a paragraph instead of a single line.

**Comment by lwjohnst86** [comment]
See #14
